#Kubectl scale rc --replicas=2  firstreplicationcontroller
apiVersion: v1
kind: ReplicationController
metadata:
  name: firstreplicationcontroller
spec:
  replicas: 5
  selector:
    type: app #( aquire if any existings pods - Match based selector). 
  template: # this is your pod specification
    metadata:
      name: firstpod
      labels:
        type: app
    spec:
      containers:
        - name: containerexrc
          image: docker.io/pintulohargcetts/nginx_custom:v1
          #ports:
          #  - containerPort: <Port>
